@startuml ExamsModule
class Exam {
  String name
  String courseCode
  DateTime examDate
}

class Credit {

}

class Result {
  String grade
  String feedback
}

class Student {
  String studentId
  String name
  List<Credit> creditsEarned
  Map<Exam, Result> examResults
}

class Teacher {
  String teacherId
  String name
  List<Exam> examsTeaching
}

Exam "" -- "" Credit : to enroll for <
Credit "" -- "" Student : is required to have <
Exam "" -- "" Result : produces >
Result "" -- "1" Student : is received by >
Exam "1" -- "1" Teacher : gives <
Result "" -- "*" Teacher : approves <
@enduml